SOURCES = 	 tabs/__init__.py\
			 tabs/Eamena.py\
			 tabs/Excel_export.py\
			 tabs/Gis_Time_controller.py\
			 tabs/Image_viewer.py\
			 tabs/Images_comparison.py\
			 tabs/Images_directory_export.py\
			 tabs/PRINTMAP.py\
			 tabs/Pdf_administrator.py\
			 tabs/Site.py\
			 tabs/Tutorial_viewer.py\
			 tabs/Upd.py\
			 tabs/hff_system_ANC_CON.py\
			 tabs/hff_system_ART_CON.py\
			 tabs/hff_system_Pottery_CON.py\
			 tabs/hff_system__ANC_mainapp.py\
			 tabs/hff_system__ART_mainapp.py\
			 tabs/hff_system__Pottery_mainapp.py\
			 tabs/hff_system__Shipwreck.py\
			 tabs/hff_system__UW_mainapp.py\
			 gui/__init__.py\
			 gui/dbmanagment.py\
			 gui/imageViewer.py\
			 gui/hff_system_ConfigDialog.py\
			 gui/hff_system_InfoDialog.py\
			 gui/hff_connection_settings_dialog.py\
			 gui/hff_remote_storage_dialog.py\
			 gui/hff_user_management_dialog.py\
			 gui/quantpanelmain.py\
			 gui/sortpanelmain.py\
			 gui/ui/mplwidget.py\
			 gui/ui/mplwidgetmatrix.py\
			 modules/db/__init__.py\
			 modules/db/hff_db_manager.py\
			 modules/db/hff_db_mapper.py\
			 modules/db/hff_db_structure.py\
			 modules/db/hff_system__conn_strings.py\
			 modules/db/hff_system__db_update.py\
			 modules/db/hff_system__utility.py\
			 modules/db/hff_concurrency_manager.py\
			 modules/db/hff_permissions_manager.py\
			 modules/utility/__init__.py\
			 modules/utility/csv_writer.py\
			 modules/utility/delegateComboBox.py\
			 modules/utility/hff_form_base.py\
			 modules/utility/hff_i18n.py\
			 modules/utility/hff_theme_manager.py\
			 modules/utility/hff_system__OS_utility.py\
			 modules/utility/hff_system__backup_dir.py\
			 modules/utility/hff_system__error_check.py\
			 modules/utility/hff_system__exp_ANCsheet_pdf.py\
			 modules/utility/hff_system__exp_ARsheet_pdf.py\
			 modules/utility/hff_system__exp_POTTERYsheet_pdf.py\
			 modules/utility/hff_system__exp_POTTERYCONsheet_pdf.py\
			 modules/utility/hff_system__exp_UWsheet_pdf.py\
			 modules/utility/hff_system__exp_shipwrecksheet_pdf.py\
			 modules/utility/hff_system__exp_site_pdf.py\
			 modules/utility/hff_system__exp_pdf_experimental.py\
			 modules/utility/hff_system__exp_pdf_utility.py\
			 modules/utility/hff_system__folder_installation.py\
			 modules/utility/hff_system__media_utility.py\
			 modules/utility/hff_system__print_utility.py\
			 modules/utility/settings.py\
			 modules/utility/VideoPlayer.py\
			 modules/utility/VideoPlayerAnchor.py\
			 modules/utility/VideoPlayerArtefact.py\
			 modules/utility/VideoPlayerPottery.py\
			 modules/utility/VideoPlayerShipwreck.py

FORMS =   	gui/ui/Eamena.ui\
			gui/ui/Excel_export.ui\
			gui/ui/Gis_Time_controller.ui\
			gui/ui/Image_Viewer.ui\
			gui/ui/Images_comparison.ui\
			gui/ui/Images_directory_export.ui\
			gui/ui/PRINTMAP.ui\
			gui/ui/Pdf_administrator.ui\
			gui/ui/Site.ui\
			gui/ui/Upd.ui\
			gui/ui/dbmanagment.ui\
			gui/ui/hff_system_ANC_CON_ui.ui\
			gui/ui/hff_system_ART_CON_ui.ui\
			gui/ui/hff_system_Pottery_CON_ui.ui\
			gui/ui/hff_system__ANC_ui.ui\
			gui/ui/hff_system__ARTLOG_ui.ui\
			gui/ui/hff_system__Pottery_ui.ui\
			gui/ui/hff_system__Shipwreck_ui.ui\
			gui/ui/hff_system__UW_ui.ui\
			gui/ui/hff_system__plugin.ui\
			gui/ui/hff_system_ConfigDialog.ui\
			gui/ui/hff_system_InfoDialog.ui\
			gui/ui/quantpanelmain.ui\
			gui/ui/sortpanelmain.ui

TRANSLATIONS = i18n/hff_plugin_it_IT.ts \
               i18n/hff_plugin_de_DE.ts \
               i18n/hff_plugin_en_US.ts \
               i18n/hff_plugin_ar_LB.ts

RESOURCES = resources/resources.qrc
