# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_UW_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogUW(object):
    def setupUi(self, DialogUW):
        DialogUW.setObjectName("DialogUW")
        DialogUW.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogUW.resize(1611, 874)
        DialogUW.setMinimumSize(QtCore.QSize(540, 400))
        DialogUW.setMouseTracking(True)
        DialogUW.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/banner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogUW.setWindowIcon(icon)
        DialogUW.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        DialogUW.setInputMethodHints(QtCore.Qt.ImhNone)
        DialogUW.setSizeGripEnabled(False)
        DialogUW.setModal(False)
        self.line_8 = QtWidgets.QFrame(DialogUW)
        self.line_8.setGeometry(QtCore.QRect(564, 155, 546, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.tabWidget = QtWidgets.QTabWidget(DialogUW)
        self.tabWidget.setGeometry(QtCore.QRect(20, 240, 1561, 621))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.comboBox_diver = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_diver.setGeometry(QtCore.QRect(10, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_diver.setFont(font)
        self.comboBox_diver.setEditable(True)
        self.comboBox_diver.setObjectName("comboBox_diver")
        self.lineEdit_surface_interval = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_surface_interval.setGeometry(QtCore.QRect(200, 310, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_surface_interval.setFont(font)
        self.lineEdit_surface_interval.setObjectName("lineEdit_surface_interval")
        self.lineEdit_bar_start = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_bar_start.setGeometry(QtCore.QRect(200, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_bar_start.setFont(font)
        self.lineEdit_bar_start.setObjectName("lineEdit_bar_start")
        self.lineEdit_max_depth = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_max_depth.setGeometry(QtCore.QRect(200, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_max_depth.setFont(font)
        self.lineEdit_max_depth.setObjectName("lineEdit_max_depth")
        self.lineEdit_bar_end = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_bar_end.setGeometry(QtCore.QRect(360, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_bar_end.setFont(font)
        self.lineEdit_bar_end.setObjectName("lineEdit_bar_end")
        self.lineEdit_breathing_mix = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_breathing_mix.setGeometry(QtCore.QRect(360, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_breathing_mix.setFont(font)
        self.lineEdit_breathing_mix.setObjectName("lineEdit_breathing_mix")
        self.lineEdit_visibility = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_visibility.setGeometry(QtCore.QRect(10, 420, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_visibility.setFont(font)
        self.lineEdit_visibility.setObjectName("lineEdit_visibility")
        self.lineEdit_temperature = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_temperature.setGeometry(QtCore.QRect(10, 360, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_temperature.setFont(font)
        self.lineEdit_temperature.setObjectName("lineEdit_temperature")
        self.label = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_7.setGeometry(QtCore.QRect(360, 9, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_8.setGeometry(QtCore.QRect(200, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setObjectName("label_8")
        self.lineEdit_bottom_time = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_bottom_time.setGeometry(QtCore.QRect(200, 240, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_bottom_time.setFont(font)
        self.lineEdit_bottom_time.setObjectName("lineEdit_bottom_time")
        self.label_12 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_12.setGeometry(QtCore.QRect(200, 220, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_13.setGeometry(QtCore.QRect(200, 290, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_14.setGeometry(QtCore.QRect(200, 150, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_15.setGeometry(QtCore.QRect(360, 150, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_16.setGeometry(QtCore.QRect(360, 80, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_17.setGeometry(QtCore.QRect(10, 400, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_18.setGeometry(QtCore.QRect(10, 340, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_19.setGeometry(QtCore.QRect(200, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_20.setGeometry(QtCore.QRect(10, 530, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_20.setObjectName("label_20")
        self.label_49 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_49.setGeometry(QtCore.QRect(360, 360, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_50.setGeometry(QtCore.QRect(360, 290, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_50.setObjectName("label_50")
        self.lineEdit_video_nbr = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_video_nbr.setGeometry(QtCore.QRect(360, 380, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_video_nbr.setFont(font)
        self.lineEdit_video_nbr.setObjectName("lineEdit_video_nbr")
        self.lineEdit_photo_nbr = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_photo_nbr.setGeometry(QtCore.QRect(360, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_photo_nbr.setFont(font)
        self.lineEdit_photo_nbr.setObjectName("lineEdit_photo_nbr")
        self.label_51 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_51.setGeometry(QtCore.QRect(360, 220, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_51.setObjectName("label_51")
        self.lineEdit_camera_of = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_camera_of.setGeometry(QtCore.QRect(360, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_camera_of.setFont(font)
        self.lineEdit_camera_of.setObjectName("lineEdit_camera_of")
        self.tableWidget_photo = QtWidgets.QTableWidget(self.tabWidgetPage1)
        self.tableWidget_photo.setGeometry(QtCore.QRect(550, 0, 1031, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_photo.sizePolicy().hasHeightForWidth())
        self.tableWidget_photo.setSizePolicy(sizePolicy)
        self.tableWidget_photo.setBaseSize(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tableWidget_photo.setFont(font)
        self.tableWidget_photo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_photo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_photo.setLineWidth(2)
        self.tableWidget_photo.setMidLineWidth(1)
        self.tableWidget_photo.setAutoScrollMargin(16)
        self.tableWidget_photo.setAlternatingRowColors(True)
        self.tableWidget_photo.setColumnCount(1)
        self.tableWidget_photo.setObjectName("tableWidget_photo")
        self.tableWidget_photo.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_photo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_photo.setHorizontalHeaderItem(0, item)
        self.tableWidget_photo.horizontalHeader().setDefaultSectionSize(1000)
        self.tableWidget_photo.verticalHeader().setMinimumSectionSize(22)
        self.label_52 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_52.setGeometry(QtCore.QRect(10, 460, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_52.setObjectName("label_52")
        self.tableWidget_video = QtWidgets.QTableWidget(self.tabWidgetPage1)
        self.tableWidget_video.setGeometry(QtCore.QRect(550, 300, 1021, 251))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tableWidget_video.setFont(font)
        self.tableWidget_video.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_video.setLineWidth(2)
        self.tableWidget_video.setMidLineWidth(1)
        self.tableWidget_video.setAlternatingRowColors(True)
        self.tableWidget_video.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_video.setObjectName("tableWidget_video")
        self.tableWidget_video.setColumnCount(1)
        self.tableWidget_video.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_video.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_video.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.Dense6Pattern)
        item.setForeground(brush)
        self.tableWidget_video.setItem(0, 0, item)
        self.tableWidget_video.horizontalHeader().setDefaultSectionSize(1000)
        self.pushButton_insert_row_photo = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_insert_row_photo.setGeometry(QtCore.QRect(550, 260, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_insert_row_photo.setFont(font)
        self.pushButton_insert_row_photo.setObjectName("pushButton_insert_row_photo")
        self.pushButton_remove_row_photo = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_remove_row_photo.setGeometry(QtCore.QRect(670, 260, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_remove_row_photo.setFont(font)
        self.pushButton_remove_row_photo.setObjectName("pushButton_remove_row_photo")
        self.pushButton_remove_row_video = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_remove_row_video.setGeometry(QtCore.QRect(660, 560, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_remove_row_video.setFont(font)
        self.pushButton_remove_row_video.setObjectName("pushButton_remove_row_video")
        self.pushButton_insert_row_video = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_insert_row_video.setGeometry(QtCore.QRect(550, 560, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_insert_row_video.setFont(font)
        self.pushButton_insert_row_video.setObjectName("pushButton_insert_row_video")
        self.lineEdit_time_in = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_time_in.setGeometry(QtCore.QRect(200, 31, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_time_in.setFont(font)
        self.lineEdit_time_in.setObjectName("lineEdit_time_in")
        self.lineEdit_time_out = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_time_out.setGeometry(QtCore.QRect(360, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_time_out.setFont(font)
        self.lineEdit_time_out.setObjectName("lineEdit_time_out")
        self.comboBox_buddy = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_buddy.setGeometry(QtCore.QRect(10, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_buddy.setFont(font)
        self.comboBox_buddy.setEditable(True)
        self.comboBox_buddy.setObjectName("comboBox_buddy")
        self.comboBox_additional_diver = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_additional_diver.setGeometry(QtCore.QRect(10, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_additional_diver.setFont(font)
        self.comboBox_additional_diver.setEditable(True)
        self.comboBox_additional_diver.setObjectName("comboBox_additional_diver")
        self.comboBox_standby_diver = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_standby_diver.setGeometry(QtCore.QRect(10, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_standby_diver.setFont(font)
        self.comboBox_standby_diver.setEditable(True)
        self.comboBox_standby_diver.setObjectName("comboBox_standby_diver")
        self.comboBox_tender = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_tender.setGeometry(QtCore.QRect(10, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_tender.setFont(font)
        self.comboBox_tender.setEditable(True)
        self.comboBox_tender.setObjectName("comboBox_tender")
        self.comboBox_wind = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_wind.setGeometry(QtCore.QRect(10, 550, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_wind.setFont(font)
        self.comboBox_wind.setEditable(True)
        self.comboBox_wind.setObjectName("comboBox_wind")
        self.comboBox_currents = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.comboBox_currents.setGeometry(QtCore.QRect(10, 490, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_currents.setFont(font)
        self.comboBox_currents.setEditable(True)
        self.comboBox_currents.setObjectName("comboBox_currents")
        self.comboBox_currents.addItem("")
        self.comboBox_currents.setItemText(0, "")
        self.comboBox_currents.addItem("")
        self.comboBox_currents.addItem("")
        self.comboBox_currents.addItem("")
        self.label_22 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_22.setGeometry(QtCore.QRect(200, 360, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_22.setObjectName("label_22")
        self.lineEdit_dp = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lineEdit_dp.setGeometry(QtCore.QRect(200, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_dp.setFont(font)
        self.lineEdit_dp.setObjectName("lineEdit_dp")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.iconListWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.iconListWidget_2.setGeometry(QtCore.QRect(840, 20, 721, 571))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.iconListWidget_2.setFont(font)
        self.iconListWidget_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.iconListWidget_2.setProperty("showDropIndicator", True)
        self.iconListWidget_2.setDragEnabled(True)
        self.iconListWidget_2.setDragDropOverwriteMode(True)
        self.iconListWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.iconListWidget_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.iconListWidget_2.setMovement(QtWidgets.QListView.Snap)
        self.iconListWidget_2.setProperty("isWrapping", True)
        self.iconListWidget_2.setResizeMode(QtWidgets.QListView.Adjust)
        self.iconListWidget_2.setViewMode(QtWidgets.QListView.IconMode)
        self.iconListWidget_2.setUniformItemSizes(True)
        self.iconListWidget_2.setWordWrap(True)
        self.iconListWidget_2.setSelectionRectVisible(True)
        self.iconListWidget_2.setObjectName("iconListWidget_2")
        self.iconListWidget = QtWidgets.QListWidget(self.tab_2)
        self.iconListWidget.setGeometry(QtCore.QRect(-5, 21, 751, 571))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.iconListWidget.setFont(font)
        self.iconListWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.iconListWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.iconListWidget.setProperty("showDropIndicator", True)
        self.iconListWidget.setDragEnabled(True)
        self.iconListWidget.setDragDropOverwriteMode(True)
        self.iconListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.iconListWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.iconListWidget.setMovement(QtWidgets.QListView.Snap)
        self.iconListWidget.setProperty("isWrapping", True)
        self.iconListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.iconListWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.iconListWidget.setUniformItemSizes(True)
        self.iconListWidget.setWordWrap(True)
        self.iconListWidget.setSelectionRectVisible(True)
        self.iconListWidget.setObjectName("iconListWidget")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(0, 0, 741, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(840, 0, 721, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_comments = QtWidgets.QTextEdit(self.tab)
        self.textEdit_comments.setGeometry(QtCore.QRect(10, 510, 1531, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_comments.setFont(font)
        self.textEdit_comments.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_comments.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_comments.setObjectName("textEdit_comments")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 490, 1531, 20))
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setObjectName("label_11")
        self.textEdit_task = QtWidgets.QTextEdit(self.tab)
        self.textEdit_task.setGeometry(QtCore.QRect(10, 30, 1531, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_task.setFont(font)
        self.textEdit_task.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_task.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_task.setObjectName("textEdit_task")
        self.label_task = QtWidgets.QLabel(self.tab)
        self.label_task.setGeometry(QtCore.QRect(10, 10, 1531, 20))
        self.label_task.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_task.setObjectName("label_task")
        self.textEdit_result = QtWidgets.QTextEdit(self.tab)
        self.textEdit_result.setGeometry(QtCore.QRect(10, 270, 1531, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_result.setFont(font)
        self.textEdit_result.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_result.setObjectName("textEdit_result")
        self.label_result = QtWidgets.QLabel(self.tab)
        self.label_result.setGeometry(QtCore.QRect(10, 250, 1531, 20))
        self.label_result.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result.setObjectName("label_result")
        self.tabWidget.addTab(self.tab, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.pushButton_exppdf = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_exppdf.setGeometry(QtCore.QRect(30, 30, 121, 30))
        self.pushButton_exppdf.setObjectName("pushButton_exppdf")
        self.pushButton_exptab = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_exptab.setGeometry(QtCore.QRect(30, 80, 121, 28))
        self.pushButton_exptab.setObjectName("pushButton_exptab")
        self.pushButton_explist = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_explist.setGeometry(QtCore.QRect(30, 130, 121, 28))
        self.pushButton_explist.setObjectName("pushButton_explist")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabWidgetPage3)
        self.tabWidget_2.setGeometry(QtCore.QRect(150, 0, 951, 581))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_8)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButtonQuant = QtWidgets.QPushButton(self.tab_8)
        self.pushButtonQuant.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonQuant.setObjectName("pushButtonQuant")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButtonQuant)
        self.widget = Mplwidget(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 460))
        self.widget.setStyleSheet("background-color: rgb(239, 236, 236);")
        self.widget.setObjectName("widget")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.pushButton_gisview = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_gisview.setGeometry(QtCore.QRect(30, 180, 121, 28))
        self.pushButton_gisview.setObjectName("pushButton_gisview")
        self.toolButtonPreviewMedia = QtWidgets.QToolButton(self.tabWidgetPage3)
        self.toolButtonPreviewMedia.setGeometry(QtCore.QRect(30, 220, 111, 22))
        self.toolButtonPreviewMedia.setToolTip("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/GIS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon1)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setChecked(True)
        self.toolButtonPreviewMedia.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreviewMedia.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreviewMedia.setObjectName("toolButtonPreviewMedia")
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.layoutWidget = QtWidgets.QWidget(DialogUW)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 1501, 178))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtWidgets.QLabel(self.layoutWidget)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_sort.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sort.setText("")
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_rec_corrente.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_rec_tot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 3, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_new_rec = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_new_rec.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon2)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_last_rec = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_last_rec.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon3)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon4)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_search_go = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_search_go.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon5)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_sort.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon6)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_view_all.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon7)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        self.pushButton_new_search = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_new_search.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_prev_rec = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_prev_rec.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_prev_rec.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon9)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 3, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon10)
        self.pushButton_delete.setFlat(False)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_next_rec = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_next_rec.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon11)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_first_rec = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_first_rec.sizePolicy().hasHeightForWidth())
        self.pushButton_first_rec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_first_rec.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon12)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.comboBox_area_reference = QtWidgets.QComboBox(DialogUW)
        self.comboBox_area_reference.setGeometry(QtCore.QRect(800, 200, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_area_reference.setFont(font)
        self.comboBox_area_reference.setEditable(True)
        self.comboBox_area_reference.setObjectName("comboBox_area_reference")
        self.label_9 = QtWidgets.QLabel(DialogUW)
        self.label_9.setGeometry(QtCore.QRect(680, 200, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(DialogUW)
        self.label_10.setGeometry(QtCore.QRect(450, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setObjectName("label_10")
        self.label_21 = QtWidgets.QLabel(DialogUW)
        self.label_21.setGeometry(QtCore.QRect(230, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_21.setObjectName("label_21")
        self.lineEdit_divelog_id = QtWidgets.QLineEdit(DialogUW)
        self.lineEdit_divelog_id.setGeometry(QtCore.QRect(320, 200, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_divelog_id.setFont(font)
        self.lineEdit_divelog_id.setObjectName("lineEdit_divelog_id")
        self.lineEdit_date = QtWidgets.QLineEdit(DialogUW)
        self.lineEdit_date.setGeometry(QtCore.QRect(1070, 200, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_date.setFont(font)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.label_6 = QtWidgets.QLabel(DialogUW)
        self.label_6.setGeometry(QtCore.QRect(960, 200, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setObjectName("label_6")
        self.comboBox_years = QtWidgets.QComboBox(DialogUW)
        self.comboBox_years.setGeometry(QtCore.QRect(540, 200, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_years.setFont(font)
        self.comboBox_years.setEditable(True)
        self.comboBox_years.setObjectName("comboBox_years")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.label_25 = QtWidgets.QLabel(DialogUW)
        self.label_25.setGeometry(QtCore.QRect(1220, 200, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(DialogUW)
        self.label_26.setGeometry(QtCore.QRect(20, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_26.setObjectName("label_26")
        self.comboBox_sito = QtWidgets.QComboBox(DialogUW)
        self.comboBox_sito.setGeometry(QtCore.QRect(90, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setObjectName("comboBox_sito")
        self.lineEdit_layer = QtWidgets.QLineEdit(DialogUW)
        self.lineEdit_layer.setGeometry(QtCore.QRect(1340, 200, 141, 21))
        self.lineEdit_layer.setObjectName("lineEdit_layer")

        self.retranslateUi(DialogUW)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogUW)

    def retranslateUi(self, DialogUW):
        _translate = QtCore.QCoreApplication.translate
        DialogUW.setWindowTitle(_translate("DialogUW", "pyArchInit Underwater Survey "))
        self.label.setText(_translate("DialogUW", "Diver"))
        self.label_2.setText(_translate("DialogUW", "Tender"))
        self.label_3.setText(_translate("DialogUW", "Buddy"))
        self.label_4.setText(_translate("DialogUW", "Additional diver"))
        self.label_5.setText(_translate("DialogUW", "Standby diver"))
        self.label_7.setText(_translate("DialogUW", "Time out"))
        self.label_8.setText(_translate("DialogUW", "Time in"))
        self.label_12.setText(_translate("DialogUW", "Bottom time"))
        self.label_13.setText(_translate("DialogUW", "Surface interval"))
        self.label_14.setText(_translate("DialogUW", "Bar start"))
        self.label_15.setText(_translate("DialogUW", "Bar end"))
        self.label_16.setText(_translate("DialogUW", "Breathing mix"))
        self.label_17.setText(_translate("DialogUW", "Visibility"))
        self.label_18.setText(_translate("DialogUW", "Temperature"))
        self.label_19.setText(_translate("DialogUW", "Max depth"))
        self.label_20.setText(_translate("DialogUW", "Wind"))
        self.label_49.setText(_translate("DialogUW", "N Video"))
        self.label_50.setText(_translate("DialogUW", "N Photo"))
        self.lineEdit_video_nbr.setText(_translate("DialogUW", "0"))
        self.lineEdit_photo_nbr.setText(_translate("DialogUW", "0"))
        self.label_51.setText(_translate("DialogUW", "Camera of"))
        self.tableWidget_photo.setSortingEnabled(True)
        item = self.tableWidget_photo.verticalHeaderItem(0)
        item.setText(_translate("DialogUW", "1"))
        item = self.tableWidget_photo.horizontalHeaderItem(0)
        item.setText(_translate("DialogUW", "Photo id"))
        self.label_52.setText(_translate("DialogUW", "Current "))
        self.tableWidget_video.setSortingEnabled(True)
        item = self.tableWidget_video.verticalHeaderItem(0)
        item.setText(_translate("DialogUW", "1"))
        item = self.tableWidget_video.horizontalHeaderItem(0)
        item.setText(_translate("DialogUW", "Video id"))
        __sortingEnabled = self.tableWidget_video.isSortingEnabled()
        self.tableWidget_video.setSortingEnabled(False)
        self.tableWidget_video.setSortingEnabled(__sortingEnabled)
        self.pushButton_insert_row_photo.setText(_translate("DialogUW", "Insert row"))
        self.pushButton_remove_row_photo.setText(_translate("DialogUW", "Removed row"))
        self.pushButton_remove_row_video.setText(_translate("DialogUW", "Removed row"))
        self.pushButton_insert_row_video.setText(_translate("DialogUW", "Insert row"))
        self.comboBox_currents.setItemText(1, _translate("DialogUW", "Strong"))
        self.comboBox_currents.setItemText(2, _translate("DialogUW", "Medium"))
        self.comboBox_currents.setItemText(3, _translate("DialogUW", "Low"))
        self.label_22.setText(_translate("DialogUW", "Δ P"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("DialogUW", "Dive Log Form"))
        self.iconListWidget_2.setSortingEnabled(True)
        self.iconListWidget.setSortingEnabled(True)
        self.label_23.setText(_translate("DialogUW", "Sketch"))
        self.label_24.setText(_translate("DialogUW", "Photo Environment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogUW", "Media"))
        self.label_11.setText(_translate("DialogUW", "Comments"))
        self.label_task.setText(_translate("DialogUW", "Task"))
        self.label_result.setText(_translate("DialogUW", "Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogUW", "Task"))
        self.pushButton_exppdf.setText(_translate("DialogUW", "Export PDF"))
        self.pushButton_exptab.setText(_translate("DialogUW", "Export TAB"))
        self.pushButton_explist.setText(_translate("DialogUW", "Export List"))
        self.pushButtonQuant.setText(_translate("DialogUW", "Settings"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("DialogUW", "Statistic"))
        self.pushButton_gisview.setText(_translate("DialogUW", "GIS View"))
        self.toolButtonPreviewMedia.setText(_translate("DialogUW", "Preview "))
        self.toolButtonPreviewMedia.setShortcut(_translate("DialogUW", "Ctrl+G"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("DialogUW", "Tools"))
        self.label_29.setText(_translate("DialogUW", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">DBMS Toolbar</span></p></body></html>"))
        self.label_42.setText(_translate("DialogUW", "DB Info"))
        self.label_43.setText(_translate("DialogUW", "Order"))
        self.label_34.setText(_translate("DialogUW", "Status"))
        self.label_27.setText(_translate("DialogUW", "record n."))
        self.label_rec_corrente.setText(_translate("DialogUW", "1"))
        self.label_28.setText(_translate("DialogUW", "record tot."))
        self.label_rec_tot.setText(_translate("DialogUW", "1"))
        self.pushButton_connect.setText(_translate("DialogUW", "Connection test"))
        self.pushButton_new_rec.setToolTip(_translate("DialogUW", "New record"))
        self.pushButton_new_rec.setText(_translate("DialogUW", "New rec"))
        self.pushButton_last_rec.setToolTip(_translate("DialogUW", "Last rec"))
        self.pushButton_last_rec.setText(_translate("DialogUW", "Last rec"))
        self.pushButton_save.setToolTip(_translate("DialogUW", "Save"))
        self.pushButton_save.setText(_translate("DialogUW", "Save"))
        self.pushButton_search_go.setToolTip(_translate("DialogUW", "search !!!"))
        self.pushButton_search_go.setText(_translate("DialogUW", "Go Search"))
        self.pushButton_sort.setToolTip(_translate("DialogUW", "Order by"))
        self.pushButton_sort.setText(_translate("DialogUW", "Order by"))
        self.pushButton_view_all.setToolTip(_translate("DialogUW", "View alls records"))
        self.pushButton_view_all.setText(_translate("DialogUW", "Restore setting"))
        self.pushButton_new_search.setToolTip(_translate("DialogUW", "new search"))
        self.pushButton_new_search.setText(_translate("DialogUW", "Search"))
        self.pushButton_prev_rec.setToolTip(_translate("DialogUW", "Prev rec"))
        self.pushButton_prev_rec.setText(_translate("DialogUW", "Prev rec"))
        self.pushButton_delete.setToolTip(_translate("DialogUW", "Delete record"))
        self.pushButton_delete.setText(_translate("DialogUW", "Delete"))
        self.pushButton_next_rec.setToolTip(_translate("DialogUW", "Next rec"))
        self.pushButton_next_rec.setText(_translate("DialogUW", "Next rec"))
        self.pushButton_first_rec.setToolTip(_translate("DialogUW", "First rec"))
        self.pushButton_first_rec.setText(_translate("DialogUW", "First rec"))
        self.label_9.setText(_translate("DialogUW", "Area"))
        self.label_10.setText(_translate("DialogUW", "Year"))
        self.label_21.setText(_translate("DialogUW", "DIVE ID"))
        self.label_6.setText(_translate("DialogUW", "Date"))
        self.comboBox_years.setItemText(0, _translate("DialogUW", "2013"))
        self.comboBox_years.setItemText(1, _translate("DialogUW", "2016"))
        self.comboBox_years.setItemText(2, _translate("DialogUW", "2017"))
        self.comboBox_years.setItemText(3, _translate("DialogUW", "2018"))
        self.label_25.setText(_translate("DialogUW", "Layer"))
        self.label_26.setText(_translate("DialogUW", "Site"))

from mplwidget import Mplwidget
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUW = QtWidgets.QDialog()
    ui = Ui_DialogUW()
    ui.setupUi(DialogUW)
    DialogUW.show()
    sys.exit(app.exec_())

